# ${project.name} ${project.version}
# Check out the readme for more configuration details:
# https://github.com/Pupskuchen/spigot-TimeControl#configuration

# This defines the global/default configuration
# that gets used by every world defined in "worlds"
# unless you override some or all settings for certain worlds.
defaults:
  durations:
    # Daytime duration in minutes
    day: 10
    # Nighttime duration in minutes
    night: 8
    # Make sunset pass at the same speed as the night
    sunset: "night"
    # Make sunrise pass at the same speed as the night
    sunrise: "night"
  # With night-skipping enabled, players can skip the night by sleeping.
  # This functionality honors the "playersSleepingPercentage" game rule.
  night-skipping:
    enabled: true
  # If your server doesn't have the "playersSleepingPercentage" game rule,
  # you can still control the percentage by enabling this.
  players-sleeping-percentage:
    enabled: false
    percentage: 100

# Worlds to enable ${project.name} for
# You can override the settings defined in "defaults" per world.
worlds:
  - name: "world"
