# ${project.name} ${project.version}

# Day cycle in minutes
day: 30

# Night cycle in minutes
night: 5

# Worlds to enable
worlds:
  - "world"

# when this option is enabled, you can skip the night
night-skipping:
  enabled: false

# If your server doesn't have the 'playersSleepingPercentage' game rule,
# you can still control the percentage by enabling this
players-sleeping-percentage:
  enabled: false
  percentage: 50
