name: TimeControl
main: net.pupskuchen.timecontrol.TimeControl
version: 1.0.10.beta.2
api-version: 1.19
authors: [foncused, mrgeneralq, pupskuchen]
website: https://github.com/Pupskuchen/spigot-TimeControl
