name: ${project.name}
main: net.pupskuchen.timecontrol.TimeControl
version: ${project.version}
api-version: 1.13
author: pupskuchen
website: https://github.com/Pupskuchen/spigot-TimeControl
load: STARTUP
